const http=require('http');
const dgram=require('dgram');
const fs=require('fs');
const path=require('path');
const PORT=8787,UDP_PORT=33740,PS5_PORT=33739,CONFIG_FILE='./config.json',DATA_DIR='./data',DB_FILE='./data/telemetry-v4.json';
fs.mkdirSync(DATA_DIR,{recursive:true});
let config={ps5Ip:process.env.PS5_IP||'192.168.1.68',autoSession:true,packetType:'C'};try{config={...config,...JSON.parse(fs.readFileSync(CONFIG_FILE,'utf8'))}}catch{}
let db={version:4,sessions:[],ranking:[],settings:{}};try{db={...db,...JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}}catch{}
function saveDb(){fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2))}function saveConfig(){fs.writeFileSync(CONFIG_FILE,JSON.stringify(config,null,2))}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function sum(a){return a.reduce((x,y)=>x+y,0)}
function f2(v){return Number.isFinite(v)?Number(v.toFixed(2)):0}function f3(v){return Number.isFinite(v)?Number(v.toFixed(3)):0}
function rdF(b,o){try{return b.readFloatLE(o)}catch{return 0}}function rdI32(b,o){try{return b.readInt32LE(o)}catch{return 0}}function rdI16(b,o){try{return b.readInt16LE(o)}catch{return 0}}function rdU16(b,o){try{return b.readUInt16LE(o)}catch{return 0}}function rdU8(b,o){try{return b.readUInt8(o)}catch{return 0}}
function str4(b,o){try{return b.subarray(o,o+4).toString('ascii').replace(/\0/g,'').trim()}catch{return''}}
function fmt(ms){if(!ms||ms<=0)return'--';let h=Math.floor(ms/36e5);ms%=36e5;let m=Math.floor(ms/6e4);ms%=6e4;let s=Math.floor(ms/1e3),z=Math.floor(ms%1e3);return(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+'.'+String(z).padStart(3,'0')}
function validLap(ms){return Number.isFinite(ms)&&ms>=30000&&ms<=900000}
function avg(arr){arr=arr.filter(validLap);if(!arr.length)return 0;let cut=arr.length>=10?3:(arr.length>=5?2:0),u=arr.slice().sort((a,b)=>a-b);if(cut&&u.length>cut*2)u=u.slice(cut,-cut);return u.length?Math.round(sum(u)/u.length):0}
function stdev(a){if(a.length<2)return 0;let m=sum(a)/a.length;return Math.sqrt(a.reduce((x,y)=>x+(y-m)**2,0)/a.length)}
function analysis(laps){let arr=laps.map(l=>l.ms).filter(validLap),best=arr.length?Math.min(...arr):0,last=arr.length?arr[arr.length-1]:0,total=sum(arr),am=avg(arr),cons=arr.length>1&&best?Math.max(0,100-Math.round(stdev(arr)/best*100)):(arr.length?100:0);return{laps:laps.length,bestMs:best,best:fmt(best),lastMs:last,last:fmt(last),totalMs:total,total:fmt(total),avgMs:am,average:fmt(am),deltaBest:best&&last?fmt(Math.max(0,last-best)):'--',consistency:arr.length?cons+'%':'--',grade:!arr.length?'--':cons>=97?'A+':cons>=93?'A':cons>=87?'B':cons>=78?'C':'D',heatmap:laps.map((l,i)=>({lap:i+1,time:fmt(l.ms),rating:l.ms===best?'Boa':(best&&l.ms>best*1.04?'Ruim':'Média')}))}}
function coach(parts){if(!parts.length)return['Média','Média','Média','Média'];let base=Math.max(1,...parts.map(p=>p.speed||0)),out=[];for(let i=0;i<4;i++){let c=parts.slice(Math.floor(parts.length*i/4),Math.floor(parts.length*(i+1)/4));let sp=sum(c.map(x=>x.speed||0))/(c.length||1),br=sum(c.map(x=>x.brake||0))/(c.length||1),th=sum(c.map(x=>x.throttle||0))/(c.length||1);let score=sp/base*100-br*.18+th*.05;out.push(score>=88?'Boa':score>=72?'Média':'Ruim')}return out}
function rotl(v,c){return((v<<c)|(v>>>(32-c)))>>>0}function qr(x,a,b,c,d){x[b]^=rotl((x[a]+x[d])>>>0,7);x[c]^=rotl((x[b]+x[a])>>>0,9);x[d]^=rotl((x[c]+x[b])>>>0,13);x[a]^=rotl((x[d]+x[c])>>>0,18)}
function salsaBlock(key,iv,cnt){let sig=Buffer.from('expand 32-byte k'),st=new Uint32Array(16);st[0]=sig.readUInt32LE(0);st[5]=sig.readUInt32LE(4);st[10]=sig.readUInt32LE(8);st[15]=sig.readUInt32LE(12);for(let i=0;i<4;i++)st[1+i]=key.readUInt32LE(i*4);for(let i=0;i<4;i++)st[11+i]=key.readUInt32LE(16+i*4);st[6]=iv.readUInt32LE(0);st[7]=iv.readUInt32LE(4);st[8]=cnt>>>0;st[9]=0;let x=new Uint32Array(st);for(let i=0;i<10;i++){qr(x,0,4,8,12);qr(x,5,9,13,1);qr(x,10,14,2,6);qr(x,15,3,7,11);qr(x,0,1,2,3);qr(x,5,6,7,4);qr(x,10,11,8,9);qr(x,15,12,13,14)}let out=Buffer.alloc(64);for(let i=0;i<16;i++)out.writeUInt32LE((x[i]+st[i])>>>0,i*4);return out}
function salsaXor(buf,key,iv){let out=Buffer.alloc(buf.length),cnt=0;for(let off=0;off<buf.length;off+=64){let block=salsaBlock(key,iv,cnt++);for(let i=0;i<Math.min(64,buf.length-off);i++)out[off+i]=buf[off+i]^block[i]}return out}
function packetKind(len){return len===368?'C':len===344?'~':len===316?'B':len===296?'A':'?'}
function decrypt(msg){let key=Buffer.from('Simulator Interface Packet GT7 ver 0.0').subarray(0,32),iv1;try{iv1=msg.readUInt32LE(0x40)}catch{return null}let constants=[0xDEADBEEF,0xDEADBEAF,0x55FABB4F];for(const c of constants){let iv=Buffer.alloc(8);iv.writeUInt32LE((iv1^c)>>>0,0);iv.writeUInt32LE(iv1,4);let out=salsaXor(msg,key,iv);try{if(out.readUInt32LE(0)===0x47375330)return out}catch{}}return null}
function flagsObj(v){return{raw:v,carOnTrack:!!(v&1),paused:!!(v&2),loading:!!(v&4),inGear:!!(v&8),hasTurbo:!!(v&16),revLimiter:!!(v&32),handBrake:!!(v&64),lights:!!(v&128),highBeam:!!(v&256),lowBeam:!!(v&512),asm:!!(v&1024),tcs:!!(v&2048)}}
function decodeAdvanced(d){let len=d.length,gears=rdU8(d,0x90),cur=gears&15,sug=(gears>>4)&15,flags=rdU16(d,0x8e);let adv={packetType:packetKind(len),packetId:rdI32(d,0x70),position:{x:f3(rdF(d,0x04)),y:f3(rdF(d,0x08)),z:f3(rdF(d,0x0c))},worldVelocity:{x:f3(rdF(d,0x10)),y:f3(rdF(d,0x14)),z:f3(rdF(d,0x18))},rotation:{pitch:f3(rdF(d,0x1c)),yaw:f3(rdF(d,0x20)),roll:f3(rdF(d,0x24))},orientationNorth:f3(rdF(d,0x28)),angularVelocity:{x:f3(rdF(d,0x2c)),y:f3(rdF(d,0x30)),z:f3(rdF(d,0x34))},bodyHeight:f3(rdF(d,0x38)),boost:f2(rdF(d,0x50)-1),boostRaw:f2(rdF(d,0x50)),oilPressure:f2(rdF(d,0x54)),waterTemp:f2(rdF(d,0x58)),oilTemp:f2(rdF(d,0x5c)),tyreTemp:{FL:f2(rdF(d,0x60)),FR:f2(rdF(d,0x64)),RL:f2(rdF(d,0x68)),RR:f2(rdF(d,0x6c))},dayProgression:rdI32(d,0x80),raceStartPosition:rdI16(d,0x84),preRaceNumCars:rdI16(d,0x86),minAlertRPM:rdI16(d,0x88),maxAlertRPM:rdI16(d,0x8a),calcMaxSpeed:rdI16(d,0x8c),flags:flagsObj(flags),currentGear:cur===0?'N':cur,suggestedGear:sug===15?'--':sug,roadPlane:{x:f3(rdF(d,0x94)),y:f3(rdF(d,0x98)),z:f3(rdF(d,0x9c)),distance:f3(rdF(d,0xa0))},wheelRPS:{FL:f3(rdF(d,0xa4)),FR:f3(rdF(d,0xa8)),RL:f3(rdF(d,0xac)),RR:f3(rdF(d,0xb0))},tyreRadius:{FL:f3(rdF(d,0xb4)),FR:f3(rdF(d,0xb8)),RL:f3(rdF(d,0xbc)),RR:f3(rdF(d,0xc0))},suspHeight:{FL:f3(rdF(d,0xc4)),FR:f3(rdF(d,0xc8)),RL:f3(rdF(d,0xcc)),RR:f3(rdF(d,0xd0))},clutch:f2(rdF(d,0xf4)),clutchEngagement:f2(rdF(d,0xf8)),rpmClutchToGearbox:Math.round(rdF(d,0xfc)||0),transmissionTopSpeed:f2(rdF(d,0x100)),gearRatios:Array.from({length:8},(_,i)=>f3(rdF(d,0x104+i*4))),carCode:rdI32(d,0x124)};
 if(len>=316){adv.packetB={wheelRotation:f3(rdF(d,0x128)),steeringAngularVelocity:f3(rdF(d,0x12c)),gForce:{sway:f3(rdF(d,0x130)),heave:f3(rdF(d,0x134)),surge:f3(rdF(d,0x138))}};adv.steeringAngularVelocity=adv.packetB.steeringAngularVelocity;adv.gForce=adv.packetB.gForce}
 if(len>=344){adv.packetTilda={throttleFiltered:Math.round(rdU8(d,0x13c)/2.55),brakeFiltered:Math.round(rdU8(d,0x13d)/2.55),torqueVectors:{FL:f3(rdF(d,0x140)),FR:f3(rdF(d,0x144)),RL:f3(rdF(d,0x148)),RR:f3(rdF(d,0x14c))},energyRecovery:f3(rdF(d,0x150))};adv.throttleFiltered=adv.packetTilda.throttleFiltered;adv.brakeFiltered=adv.packetTilda.brakeFiltered;adv.torqueVectors=adv.packetTilda.torqueVectors;adv.energyRecovery=adv.packetTilda.energyRecovery}
 if(len>=368){adv.packetC={surfaceType:str4(d,0x158),currentLapMs:rdI32(d,0x15c),wheelSteeringAngle:{left:f3(rdF(d,0x160)),right:f3(rdF(d,0x164))},wheelBase:f3(rdF(d,0x168)),carCategory:str4(d,0x16c)};adv.surfaceType=adv.packetC.surfaceType;adv.currentLapMs=adv.packetC.currentLapMs;adv.wheelSteeringAngle=adv.packetC.wheelSteeringAngle;adv.wheelBase=adv.packetC.wheelBase;adv.carCategory=adv.packetC.carCategory}
 return adv}
let live={connected:false,status:'aguardando_pacotes',decodeOk:false,updatedAt:null,packetSize:0,packetVersion:'?',ps5Ip:config.ps5Ip,sessionState:'WAITING',currentSessionId:null,velocidade:0,velocidadeMaxima:0,rpm:0,marcha:'N',marchaNumero:0,marchaSugerida:'--',acelerador:0,freio:0,combustivel:null,combustivelPorcentagem:null,fuelCapacity:null,melhorVolta:'--',ultimaVolta:'--',voltaAtualTempo:'--',tempoTotalCorrida:'--',mediaVoltas:'--',voltasCompletadas:0,voltasCorrigidas:0,voltasCorridas:0,totalLaps:0,lapTimes:[],analysis:analysis([]),coach:[],advanced:{},motecChannels:{},lapDebug:{},note:'Core V4 Raspberry ativo'};
let active=null,lastLapMs=0,lastLapNo=0,currentLap=0,currentLapAt=0,movingSince=0,stoppedSince=0,samples=[];
function startSession(name='Nova seção'){active={id:'s-'+Date.now(),name,startedAt:new Date().toISOString(),endedAt:null,laps:[],coach:[],maxSpeed:0,analysis:analysis([]),samples:[]};Object.assign(live,{sessionState:'RUNNING',currentSessionId:active.id,velocidadeMaxima:0,melhorVolta:'--',ultimaVolta:'--',tempoTotalCorrida:'--',mediaVoltas:'--',voltasCompletadas:0,voltasCorrigidas:0,voltasCorridas:0,lapTimes:[],analysis:analysis([]),coach:[]});lastLapMs=0;lastLapNo=0;currentLap=0;currentLapAt=0;samples=[];return active}
function finishSession(name){if(!active)return null;if(name)active.name=String(name).slice(0,80);active.endedAt=new Date().toISOString();active.analysis=analysis(active.laps);db.sessions.unshift(active);db.sessions=db.sessions.slice(0,300);if(active.analysis.bestMs)db.ranking.push({sessionId:active.id,name:active.name,date:active.endedAt,bestMs:active.analysis.bestMs,best:active.analysis.best,laps:active.laps.length});db.ranking=db.ranking.sort((a,b)=>a.bestMs-b.bestMs).slice(0,100);saveDb();let done=active;active=null;live.sessionState='FINISHED';live.currentSessionId=null;return done}
function registerLap(ms,no){if(!validLap(ms))return false;if(!active)startSession('Sessão automática');let token=no+':'+ms;if(active.laps.some(l=>l.token===token))return false;let parts=coach(samples.splice(0));let rec={lap:active.laps.length+1,ms,time:fmt(ms),token,at:new Date().toISOString(),maxSpeed:live.velocidadeMaxima,coach:parts};active.laps.push(rec);active.maxSpeed=Math.max(active.maxSpeed||0,live.velocidadeMaxima||0);active.coach.unshift({lap:rec.lap,time:rec.time,parts});active.analysis=analysis(active.laps);Object.assign(live,{analysis:active.analysis,coach:active.coach.slice(0,12),lapTimes:active.laps.map(l=>l.time),tempoTotalCorrida:active.analysis.total,mediaVoltas:active.analysis.average,melhorVolta:active.analysis.best,ultimaVolta:rec.time,voltasCompletadas:active.laps.length,voltasCorrigidas:active.laps.length,voltasCorridas:active.laps.length});return true}
function autoSession(){let now=Date.now(),moving=live.velocidade>20&&live.rpm>1500&&live.marchaNumero>0;if(!active&&config.autoSession&&moving){movingSince=movingSince||now;if(now-movingSince>5000)startSession('Sessão automática')}else if(!moving)movingSince=0;if(active){let stopped=live.velocidade<5;if(stopped)stoppedSince=stoppedSince||now;else stoppedSince=0;let last=active.laps.length?new Date(active.laps[active.laps.length-1].at).getTime():new Date(active.startedAt).getTime();if(stopped&&now-stoppedSince>30000&&now-last>60000)finishSession()}}
function decode(msg){let d=decrypt(msg);if(!d)return false;let speed=rdF(d,0x4C)*3.6,rpm=rdF(d,0x3C),gears=rdU8(d,0x90),gear=gears&15,sug=(gears>>4)&15,th=rdU8(d,0x91)/2.55,br=rdU8(d,0x92)/2.55,lapNo=rdI16(d,0x74),totalLaps=rdI16(d,0x76),best=rdI32(d,0x78),last=rdI32(d,0x7C),fuel=rdF(d,0x44),cap=rdF(d,0x48),now=Date.now();let adv=decodeAdvanced(d);live.advanced=adv;live.motecChannels={speedKmh:f2(speed),rpm:Math.round(rpm||0),throttle:clamp(Math.round(th),0,100),brake:clamp(Math.round(br),0,100),gear:gear===0?'N':gear,suggestedGear:adv.suggestedGear,fuel:f2(fuel),boost:adv.boost,oilPressure:adv.oilPressure,oilTemp:adv.oilTemp,waterTemp:adv.waterTemp,tyreTemp:adv.tyreTemp,wheelRPS:adv.wheelRPS,suspHeight:adv.suspHeight,clutch:adv.clutch,gForce:adv.gForce||{},steeringAngularVelocity:adv.steeringAngularVelocity||0,wheelSteeringAngle:adv.wheelSteeringAngle||{},surfaceType:adv.surfaceType||'',carCategory:adv.carCategory||'',carCode:adv.carCode,packetId:adv.packetId};live.lapDebug={packetSize:d.length,knownOffsets:{currentLap_0x74_i16:lapNo,totalLaps_0x76_i16:totalLaps,bestLap_0x78_i32:best,lastLap_0x7c_i32:last,packetId_0x70:adv.packetId,packetType:adv.packetType}};live.velocidade=Number.isFinite(speed)&&speed>=0&&speed<600?Math.round(speed):0;live.rpm=Number.isFinite(rpm)&&rpm>=0&&rpm<20000?Math.round(rpm):0;live.marcha=gear===0?'N':String(gear);live.marchaNumero=gear;live.marchaSugerida=sug===15?'--':String(sug);live.acelerador=clamp(Math.round(th),0,100);live.freio=clamp(Math.round(br),0,100);live.combustivel=Number.isFinite(fuel)?Number(fuel.toFixed(2)):null;live.fuelCapacity=Number.isFinite(cap)?Number(cap.toFixed(2)):null;live.combustivelPorcentagem=cap>0?Math.round(fuel/cap*100):null;live.totalLaps=totalLaps>0?totalLaps:0;if(active)live.velocidadeMaxima=Math.max(live.velocidadeMaxima,live.velocidade);samples.push({speed:live.velocidade,rpm:live.rpm,throttle:live.acelerador,brake:live.freio,gForce:adv.gForce||{},steering:adv.steeringAngularVelocity||0,at:now});if(active&&active.samples&&active.samples.length<12000)active.samples.push({...live.motecChannels,at:now});if(samples.length>1000)samples=samples.slice(-1000);let currentLapMs=adv.currentLapMs&&adv.currentLapMs>0?adv.currentLapMs:0;if(lapNo>0&&lapNo!==currentLap){currentLap=lapNo;currentLapAt=now}live.voltaAtualTempo=currentLapMs?fmt(currentLapMs):(currentLapAt&&lapNo>0?fmt(now-currentLapAt):'--');if(!active&&best>0)live.melhorVolta=fmt(best);if(last>0&&lapNo>1&&(last!==lastLapMs||lapNo!==lastLapNo)){lastLapMs=last;lastLapNo=lapNo;registerLap(last,lapNo)}autoSession();live.decodeOk=true;live.status='recebendo_udp_decodificado';live.note='Core V4 avançado: campos GT7 UDP/MoTeC ativos no Raspberry';return true}
function resetLive(){startSession('Nova seção');Object.assign(live,{velocidade:0,rpm:0,marcha:'N',marchaNumero:0,acelerador:0,freio:0,combustivel:null,combustivelPorcentagem:null})}
function js(res,obj,code=200){res.writeHead(code,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(obj))}function body(req){return new Promise(r=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>r(b))})}
const udp=dgram.createSocket('udp4'),hb=dgram.createSocket('udp4');udp.on('message',msg=>{live.connected=true;live.updatedAt=Date.now();live.packetSize=msg.length;live.packetVersion=packetKind(msg.length);live.ps5Ip=config.ps5Ip;if(!decode(msg)){live.decodeOk=false;live.status='recebendo_udp_sem_decode'}});udp.bind(UDP_PORT,'0.0.0.0',()=>console.log('UDP ouvindo '+UDP_PORT));setInterval(()=>{let b=Buffer.from(String(config.packetType||'C').slice(0,1));hb.send(b,0,b.length,PS5_PORT,config.ps5Ip,()=>{});if(live.updatedAt&&Date.now()-live.updatedAt>5000){live.connected=false;live.status='aguardando_pacotes'}},1000);
http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return js(res,{ok:true});let u=new URL(req.url,'http://x');if(u.pathname==='/'||u.pathname==='/api/health')return js(res,{ok:true,app:'Telemetria v4 Core Raspberry',version:4,status:live.status,sessionState:live.sessionState,endpoints:['/api/fields','/api/current-session','/api/sessions','/api/ranking','/api/coach','/api/advanced','/api/motec','/api/session/start','/api/session/finish','/api/reset','/api/config']});if(['/api/fields','/api/live','/api/telemetry'].includes(u.pathname))return js(res,live);if(u.pathname==='/api/advanced')return js(res,{ok:true,advanced:live.advanced,motecChannels:live.motecChannels});if(u.pathname==='/api/motec')return js(res,{ok:true,channels:live.motecChannels,sessionId:live.currentSessionId});if(u.pathname==='/api/current-session')return js(res,{ok:true,active,live});if(u.pathname==='/api/sessions'&&req.method==='GET')return js(res,{ok:true,sessions:db.sessions,active});if(u.pathname==='/api/ranking')return js(res,{ok:true,ranking:db.ranking});if(u.pathname==='/api/coach')return js(res,{ok:true,coach:live.coach});if(u.pathname==='/api/debug-laps')return js(res,{ok:true,lapDebug:live.lapDebug,lapTimes:live.lapTimes,analysis:live.analysis});if(u.pathname==='/api/config'&&req.method==='GET')return js(res,{ok:true,config,bridge:{port:PORT,udpPort:UDP_PORT,ps5Port:PS5_PORT},dataFile:DB_FILE});if(u.pathname==='/api/config'&&req.method==='POST'){try{let j=JSON.parse(await body(req)||'{}');if(j.ps5Ip){config.ps5Ip=String(j.ps5Ip).trim();live.ps5Ip=config.ps5Ip}if(typeof j.autoSession==='boolean')config.autoSession=j.autoSession;if(j.packetType)config.packetType=String(j.packetType).slice(0,1);saveConfig();return js(res,{ok:true,config})}catch(e){return js(res,{ok:false,error:String(e)},400)}}if(u.pathname==='/api/session/start'&&req.method==='POST'){let j={};try{j=JSON.parse(await body(req)||'{}')}catch{}return js(res,{ok:true,session:startSession(j.name||'Nova seção')})}if(u.pathname==='/api/session/finish'&&req.method==='POST'){let j={};try{j=JSON.parse(await body(req)||'{}')}catch{}return js(res,{ok:true,session:finishSession(j.name)})}if(u.pathname==='/api/sessions'&&req.method==='POST'){try{let j=JSON.parse(await body(req)||'{}'),s=active?finishSession(j.name):{id:'manual-'+Date.now(),name:String(j.name||'Seção manual').slice(0,80),startedAt:j.date||new Date().toISOString(),endedAt:new Date().toISOString(),laps:j.lapRecords||[],analysis:j.analysis||{},maxSpeed:j.max||0};if(s&&!db.sessions.some(x=>x.id===s.id)){db.sessions.unshift(s);saveDb()}return js(res,{ok:true,session:s,count:db.sessions.length})}catch(e){return js(res,{ok:false,error:String(e)},400)}}if(u.pathname==='/api/reset'&&req.method==='POST'){resetLive();return js(res,{ok:true,live})}return js(res,{ok:true,app:'Telemetria v4 Core Raspberry'})}).listen(PORT,'0.0.0.0',()=>console.log('HTTP em '+PORT+' PS5='+config.ps5Ip+' packet='+config.packetType));
