const express=require('express'),http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),dgram=require('dgram');
const PORT=+process.env.PORT||8787,ROOT=process.cwd(),DATA_DIR=path.join(ROOT,'bridge','data'),DATA_FILE=path.join(DATA_DIR,'telemetry-v4.json');
const KEY=Buffer.from('Simulator Interface Packet GT7 ver 0.0','utf8').subarray(0,32);const V='4.0.1-stitch-bridge';
const DEF={version:V,ps5Ip:process.env.PS5_IP||'192.168.1.100',udpPort:+process.env.GT7_UDP_PORT||33740,heartbeatPort:+process.env.GT7_HEARTBEAT_PORT||33739,heartbeatPacket:process.env.GT7_PACKET_VERSION||'A',defaultTrack:'GT7',defaultCar:'GT7 Car',defaultTires:'RM',driver:'Sergio'};
const now=()=>new Date().toISOString(),round=(v,d=0)=>Number((Number(v)||0).toFixed(d)),id=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
let store={config:DEF,live:null,activeSessionId:null,sessions:[],ranking:{},coach:[],layouts:{}};let lastPacketAt=0,lastLapMs=null,lastLapNo=0,wsClients=new Set();
function load(){try{store={...store,...JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))};store.config={...DEF,...store.config}}catch{} if(!store.live)store.live=blankLive()}function save(){fs.mkdirSync(DATA_DIR,{recursive:true});fs.writeFileSync(DATA_FILE,JSON.stringify(store,null,2))}function schedule(){clearTimeout(schedule.t);schedule.t=setTimeout(save,250)}
function health(){let temp=null;try{let f='/sys/class/thermal/thermal_zone0/temp';if(fs.existsSync(f))temp=round(+fs.readFileSync(f,'utf8')/1000,1)}catch{}return{hostname:os.hostname(),uptimeSec:Math.round(os.uptime()),cpuLoad1:round(os.loadavg()[0],2),ramUsedPct:round((1-os.freemem()/os.totalmem())*100,1),temperatureC:temp}}
function blankLive(){return{connected:false,source:'idle',timestamp:null,packetAgeMs:null,packetCount:0,packetVersion:'-',speedKmh:0,rpm:0,gear:'N',suggestedGear:0,throttlePct:0,brakePct:0,fuelLiters:null,fuelCapacityLiters:null,fuelPct:null,lapOnGt7:0,totalLaps:0,bestLapMs:null,lastLapMs:null,currentLapMs:null,maxSpeedSessionKmh:0,tireTemp:{fl:0,fr:0,rl:0,rr:0},gForce:{lat:0,long:0,vert:0},health:health()}}
function active(){return store.sessions.find(s=>s.id===store.activeSessionId)||null}function startSession(body={}){let s={id:id('session'),name:body.name||'Seção GT7 '+new Date().toLocaleString('pt-BR'),status:'active',startedAt:now(),driver:store.config.driver,track:body.track||store.config.defaultTrack,car:body.car||store.config.defaultCar,tires:body.tires||store.config.defaultTires,laps:[],totalTimeMs:0,bestLapMs:null,lastLapMs:null,avgLapMs:null,validLaps:0,maxSpeedKmh:0,consistencyPct:0,udmScore:0,grade:'--',coachSummary:'Aguardando voltas.'};store.sessions.unshift(s);store.activeSessionId=s.id;schedule();return s}function finishSession(name){let s=active();if(!s)return null;if(name)s.name=name;s.status='finished';s.finishedAt=now();store.activeSessionId=null;recalc(s);schedule();return s}
function recalc(s){s.validLaps=s.laps.length;s.totalTimeMs=s.laps.reduce((a,l)=>a+l.timeMs,0);s.bestLapMs=s.laps.length?Math.min(...s.laps.map(l=>l.timeMs)):null;s.lastLapMs=s.laps.length?s.laps[s.laps.length-1].timeMs:null;s.maxSpeedKmh=s.laps.length?Math.max(...s.laps.map(l=>l.maxSpeedKmh||0),s.maxSpeedKmh||0):s.maxSpeedKmh||0;let arr=s.laps.map(l=>l.timeMs).sort((a,b)=>a-b),cut=arr.length>=10?3:(arr.length>=5?2:0),used=arr.length>cut*2?arr.slice(cut,-cut):arr;s.avgLapMs=used.length?Math.round(used.reduce((a,b)=>a+b,0)/used.length):null;if(s.avgLapMs&&s.bestLapMs){let spread=Math.max(...arr)-Math.min(...arr);s.consistencyPct=Math.max(0,Math.min(100,Math.round(100-spread/1000*8)));s.udmScore=Math.round(Math.min(100,Math.max(0,60+s.consistencyPct*.35+(s.bestLapMs/s.avgLapMs)*10)));}s.grade=s.udmScore>=95?'A+':s.udmScore>=88?'A':s.udmScore>=78?'B':s.udmScore>=65?'C':s.udmScore?'D':'--';s.coachSummary=s.validLaps<2?'Complete mais voltas para comparar.':s.lastLapMs===s.bestLapMs?'Melhor volta da sessão. Boa consistência.':`Última volta ${Math.round((s.lastLapMs-s.bestLapMs)/1000*10)/10}s acima da melhor.`;rebuildRanking()}
function addLap(ms,live){if(!ms||ms<15000||ms>900000)return;let s=active()||startSession({});let lap={id:id('lap'),number:s.laps.length+1,timeMs:Math.round(ms),timestamp:now(),maxSpeedKmh:live.maxSpeedSessionKmh||live.speedKmh||0,avgSpeedKmh:0,grade:'OK'};s.laps.push(lap);recalc(s);store.coach.unshift({at:now(),message:s.coachSummary,grade:s.grade,sessionId:s.id});schedule();broadcast({type:'lap',live:store.live,session:s})}
function rebuildRanking(){let all=store.sessions.flatMap(s=>s.laps.map(l=>({session:s.name,track:s.track,car:s.car,tires:s.tires,timeMs:l.timeMs,bestLapMs:l.timeMs,grade:s.grade,at:l.timestamp}))).sort((a,b)=>a.timeMs-b.timeMs);store.ranking={geral:all.slice(0,50),porCarro:group(all,'car'),porPista:group(all,'track'),porPneu:group(all,'tires')}}function group(a,k){let o={};for(let x of a){let n=x[k]||'--';(o[n] ||= []).push(x)}for(let k in o)o[k]=o[k].slice(0,20);return o}
function qr(x,a,b,c,d){x[b]^=rot((x[a]+x[d])|0,7);x[c]^=rot((x[b]+x[a])|0,9);x[d]^=rot((x[c]+x[b])|0,13);x[a]^=rot((x[d]+x[c])|0,18)}function rot(v,c){return(v<<c)|(v>>>(32-c))}function u32(b,o){return b[o]|b[o+1]<<8|b[o+2]<<16|b[o+3]<<24}function put(b,o,v){b[o]=v&255;b[o+1]=v>>>8&255;b[o+2]=v>>>16&255;b[o+3]=v>>>24&255}
function block(key,nonce,n){let c=Buffer.from('expand 32-byte k'),x=[u32(c,0),u32(key,0),u32(key,4),u32(key,8),u32(key,12),u32(c,4),u32(nonce,0),u32(nonce,4),n,0,u32(c,8),u32(key,16),u32(key,20),u32(key,24),u32(key,28),u32(c,12)],z=x.slice();for(let i=0;i<10;i++){qr(z,0,4,8,12);qr(z,5,9,13,1);qr(z,10,14,2,6);qr(z,15,3,7,11);qr(z,0,1,2,3);qr(z,5,6,7,4);qr(z,10,11,8,9);qr(z,15,12,13,14)}let out=Buffer.alloc(64);for(let i=0;i<16;i++)put(out,i*4,(z[i]+x[i])|0);return out}function salsa(msg,nonce,key){let out=Buffer.alloc(msg.length),n=0;for(let i=0;i<msg.length;i+=64){let s=block(key,nonce,n++);for(let j=0;j<64&&i+j<msg.length;j++)out[i+j]=msg[i+j]^s[j]}return out}
function decrypt(raw){let map={296:['A',0xDEADBEAF],316:['B',0xDEADBEEF],344:['~',0x55FABB4F],368:['C',0xDEADBEEF]},m=map[raw.length];if(!m)return null;let seed=raw.readUInt32LE(0x40)^m[1],nonce=Buffer.alloc(8);nonce.writeUInt32LE(seed>>>0,0);nonce.writeUInt32LE(0,4);return{version:m[0],data:salsa(raw,nonce,KEY)}}function rf(b,o){return o+4<=b.length?b.readFloatLE(o):0}function ri(b,o){return o+4<=b.length?b.readInt32LE(o):0}
function decode(raw){try{let d=decrypt(raw);if(!d)return null;let b=d.data,flags=ri(b,0x8c),fuel=rf(b,0x44),cap=rf(b,0x48),speed=round(rf(b,0x4c)*3.6,1),rpm=Math.round(rf(b,0x3c)),last=ri(b,0x78),best=ri(b,0x7c),cur=ri(b,0x80);return{packetVersion:d.version,speedKmh:speed,rpm,gear:ri(b,0x90)&15,suggestedGear:(ri(b,0x90)>>4)&15,throttlePct:round(rf(b,0x74)*100,1),brakePct:round(rf(b,0x84)*100,1),fuelLiters:fuel||null,fuelCapacityLiters:cap||null,fuelPct:cap?round(fuel/cap*100,1):null,lapOnGt7:ri(b,0x70),totalLaps:ri(b,0x74),bestLapMs:best>0?best:null,lastLapMs:last>0?last:null,currentLapMs:cur>0?cur:null,flagsRaw:flags,tireTemp:{fl:round(rf(b,0x60),1),fr:round(rf(b,0x64),1),rl:round(rf(b,0x68),1),rr:round(rf(b,0x6c),1)},gForce:{lat:round(rf(b,0xec),2),long:round(rf(b,0xf4),2),vert:round(rf(b,0xf0),2)}}}catch(e){return null}}
function process(p){lastPacketAt=Date.now();let l=store.live||blankLive();Object.assign(l,p,{connected:true,source:'GT7 UDP',timestamp:now(),packetCount:(l.packetCount||0)+1,packetAgeMs:0,health:health()});l.maxSpeedSessionKmh=Math.max(l.maxSpeedSessionKmh||0,p.speedKmh||0);store.live=l;if(store.config.autoStartSession!==false&&!active()&&(p.speedKmh>5||p.lapOnGt7>0))startSession({});let s=active();if(s){s.maxSpeedKmh=Math.max(s.maxSpeedKmh||0,l.speedKmh||0);if(p.lastLapMs&&p.lastLapMs!==lastLapMs){lastLapMs=p.lastLapMs;addLap(p.lastLapMs,l)}else if(p.lapOnGt7&&p.lapOnGt7!==lastLapNo&&lastLapNo!==0&&p.lastLapMs){addLap(p.lastLapMs,l)}lastLapNo=p.lapOnGt7||lastLapNo}broadcast({type:'live',live:l,session:active()})}
function frame(s){let b=Buffer.from(s),h;if(b.length<126)h=Buffer.from([129,b.length]);else{h=Buffer.alloc(4);h[0]=129;h[1]=126;h.writeUInt16BE(b.length,2)}return Buffer.concat([h,b])}function broadcast(o){let f=frame(JSON.stringify(o));for(let s of [...wsClients])try{s.write(f)}catch{wsClients.delete(s)}}
load();const app=express(),server=http.createServer(app);app.use(express.json({limit:'10mb'}));app.use((q,r,n)=>{r.header('Access-Control-Allow-Origin','*');r.header('Access-Control-Allow-Headers','Content-Type');r.header('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(q.method==='OPTIONS')return r.sendStatus(204);n()});
app.get('/api/health',(q,r)=>{let age=lastPacketAt?Date.now()-lastPacketAt:null;store.live.connected=age!=null&&age<2500;store.live.packetAgeMs=age;store.live.health=health();r.json({ok:true,status:'ONLINE',version:V,port:PORT,udp:{ps5Ip:store.config.ps5Ip,listeningPort:store.config.udpPort,heartbeatPort:store.config.heartbeatPort,packet:store.config.heartbeatPacket},packets:store.live.packetCount,lastPacketAgeMs:age,health:store.live.health,endpoints:['/api/health','/api/live','/api/config','/api/session/start','/api/session/finish','/api/session/reset','/api/ranking','/api/coach','/ws']})});
app.get('/api/live',(q,r)=>{let age=lastPacketAt?Date.now()-lastPacketAt:null;store.live.connected=age!=null&&age<2500;store.live.packetAgeMs=age;r.json({live:store.live,session:active()})});app.get('/api/config',(q,r)=>r.json({config:store.config}));app.post('/api/config',(q,r)=>{store.config={...store.config,...q.body,version:V};schedule();r.json({ok:true,config:store.config})});app.post('/api/session/start',(q,r)=>r.json({ok:true,session:startSession(q.body||{})}));app.post('/api/session/finish',(q,r)=>r.json({ok:true,session:finishSession(q.body?.name)}));app.post('/api/session/reset',(q,r)=>{store.activeSessionId=null;startSession(q.body||{});schedule();r.json({ok:true,session:active()})});app.get('/api/sessions',(q,r)=>r.json({sessions:store.sessions.slice(0,+q.query.limit||80)}));app.get('/api/ranking',(q,r)=>{rebuildRanking();r.json({ranking:store.ranking})});app.get('/api/coach',(q,r)=>r.json({coach:store.coach.slice(0,+q.query.limit||50),current:active()?.coachSummary||'Aguardando sessão.'}));app.post('/api/debug/sample',(q,r)=>{let p={speedKmh:q.body.speedKmh||142,rpm:q.body.rpm||5316,gear:q.body.gear||4,throttlePct:q.body.throttlePct||20,brakePct:q.body.brakePct||0,fuelLiters:q.body.fuelLiters||42.4,lastLapMs:q.body.lastLapMs||0,bestLapMs:q.body.bestLapMs||0,lapOnGt7:q.body.lapOnGt7||0,tireTemp:{fl:82,fr:84,rl:92,rr:89},gForce:{lat:.2,long:.5,vert:1}};process(p);r.json({ok:true,live:store.live,session:active()})});
server.on('upgrade',(req,s)=>{if(req.url!='/ws')return s.destroy();let k=req.headers['sec-websocket-key'];if(!k||Array.isArray(k))return s.destroy();let a=crypto.createHash('sha1').update(k+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');s.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+a+'\r\n\r\n');wsClients.add(s);s.on('close',()=>wsClients.delete(s));s.on('error',()=>wsClients.delete(s));s.write(frame(JSON.stringify({type:'hello',live:store.live,session:active()})))});
app.use(express.static(path.join(ROOT,'www')));app.get('*',(q,r)=>r.sendFile(path.join(ROOT,'www','index.html')));server.listen(PORT,'0.0.0.0',()=>console.log('GT7 Telemetria V4 em http://0.0.0.0:'+PORT));
const udp=dgram.createSocket('udp4');udp.on('message',m=>{let p=decode(m);if(p)process(p)});udp.bind(store.config.udpPort,'0.0.0.0',()=>console.log('UDP GT7 '+store.config.udpPort));setInterval(()=>{try{if(store.config.ps5Ip)udp.send(Buffer.from(store.config.heartbeatPacket||'A'),store.config.heartbeatPort,store.config.ps5Ip)}catch{}},5000);
setInterval(()=>{let age=lastPacketAt?Date.now()-lastPacketAt:null;store.live.connected=age!=null&&age<2500;store.live.packetAgeMs=age;store.live.health=health();broadcast({type:'heartbeat',live:store.live,session:active()})},1000);
