const http=require('http');
const dgram=require('dgram');
const fs=require('fs');
const path=require('path');
const PORT=8787,UDP_PORT=33740,PS5_PORT=33739,CONFIG_FILE='./config.json',DATA_DIR='./data',DB_FILE='./data/telemetry-v4.json';
fs.mkdirSync(DATA_DIR,{recursive:true});
let config={ps5Ip:process.env.PS5_IP||'192.168.1.68',autoSession:true};try{config={...config,...JSON.parse(fs.readFileSync(CONFIG_FILE,'utf8'))}}catch{}
let db={version:4,sessions:[],ranking:[],settings:{}};try{db={...db,...JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}}catch{}
function saveDb(){fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2))}function saveConfig(){fs.writeFileSync(CONFIG_FILE,JSON.stringify(config,null,2))}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function sum(a){return a.reduce((x,y)=>x+y,0)}function round(v,d=2){return Number.isFinite(v)?Number(v.toFixed(d)):0}
function rdF(b,o){try{return b.readFloatLE(o)}catch{return 0}}function rdI32(b,o){try{return b.readInt32LE(o)}catch{return 0}}function rdI16(b,o){try{return b.readInt16LE(o)}catch{return 0}}function rdU8(b,o){try{return b.readUInt8(o)}catch{return 0}}
function fmt(ms){if(!ms||ms<=0)return'--';let h=Math.floor(ms/36e5);ms%=36e5;let m=Math.floor(ms/6e4);ms%=6e4;let s=Math.floor(ms/1e3),z=Math.floor(ms%1e3);return(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+'.'+String(z).padStart(3,'0')}
function validLap(ms){return Number.isFinite(ms)&&ms>=30000&&ms<=900000}function avg(arr){arr=arr.filter(validLap);if(!arr.length)return 0;let cut=arr.length>=10?3:(arr.length>=5?2:0),u=arr.slice().sort((a,b)=>a-b);if(cut&&u.length>cut*2)u=u.slice(cut,-cut);return u.length?Math.round(sum(u)/u.length):0}
function stdev(a){if(a.length<2)return 0;let m=sum(a)/a.length;return Math.sqrt(a.reduce((x,y)=>x+(y-m)**2,0)/a.length)}
function analysis(laps){let arr=laps.map(l=>l.ms).filter(validLap),best=arr.length?Math.min(...arr):0,last=arr.length?arr[arr.length-1]:0,total=sum(arr),am=avg(arr),cons=arr.length>1&&best?Math.max(0,100-Math.round(stdev(arr)/best*100)):(arr.length?100:0);return{laps:laps.length,bestMs:best,best:fmt(best),lastMs:last,last:fmt(last),totalMs:total,total:fmt(total),avgMs:am,average:fmt(am),deltaBest:best&&last?fmt(Math.max(0,last-best)):'--',consistency:arr.length?cons+'%':'--',grade:!arr.length?'--':cons>=97?'A+':cons>=93?'A':cons>=87?'B':cons>=78?'C':'D',heatmap:laps.map((l,i)=>({lap:i+1,time:fmt(l.ms),rating:l.ms===best?'Boa':(best&&l.ms>best*1.04?'Ruim':'Média')}))}}
function coach(parts){if(!parts.length)return['Média','Média','Média','Média'];let base=Math.max(1,...parts.map(p=>p.speed||0)),out=[];for(let i=0;i<4;i++){let c=parts.slice(Math.floor(parts.length*i/4),Math.floor(parts.length*(i+1)/4));let sp=sum(c.map(x=>x.speed||0))/(c.length||1),br=sum(c.map(x=>x.brake||0))/(c.length||1),th=sum(c.map(x=>x.throttle||0))/(c.length||1);let score=sp/base*100-br*.18+th*.05;out.push(score>=88?'Boa':score>=72?'Média':'Ruim')}return out}
function rotl(v,c){return((v<<c)|(v>>>(32-c)))>>>0}function qr(x,a,b,c,d){x[b]^=rotl((x[a]+x[d])>>>0,7);x[c]^=rotl((x[b]+x[a])>>>0,9);x[d]^=rotl((x[c]+x[b])>>>0,13);x[a]^=rotl((x[d]+x[c])>>>0,18)}
function salsaBlock(key,iv,cnt){let sig=Buffer.from('expand 32-byte k'),st=new Uint32Array(16);st[0]=sig.readUInt32LE(0);st[5]=sig.readUInt32LE(4);st[10]=sig.readUInt32LE(8);st[15]=sig.readUInt32LE(12);for(let i=0;i<4;i++)st[1+i]=key.readUInt32LE(i*4);for(let i=0;i<4;i++)st[11+i]=key.readUInt32LE(16+i*4);st[6]=iv.readUInt32LE(0);st[7]=iv.readUInt32LE(4);st[8]=cnt>>>0;st[9]=0;let x=new Uint32Array(st);for(let i=0;i<10;i++){qr(x,0,4,8,12);qr(x,5,9,13,1);qr(x,10,14,2,6);qr(x,15,3,7,11);qr(x,0,1,2,3);qr(x,5,6,7,4);qr(x,10,11,8,9);qr(x,15,12,13,14)}let out=Buffer.alloc(64);for(let i=0;i<16;i++)out.writeUInt32LE((x[i]+st[i])>>>0,i*4);return out}
function salsaXor(buf,key,iv){let out=Buffer.alloc(buf.length),cnt=0;for(let off=0;off<buf.length;off+=64){let block=salsaBlock(key,iv,cnt++);for(let i=0;i<Math.min(64,buf.length-off);i++)out[off+i]=buf[off+i]^block[i]}return out}
function decrypt(msg){try{let key=Buffer.from('Simulator Interface Packet GT7 ver 0.0').subarray(0,32),iv1=msg.readUInt32LE(0x40),iv2=(iv1^0xDEADBEAF)>>>0,iv=Buffer.alloc(8);iv.writeUInt32LE(iv2,0);iv.writeUInt32LE(iv1,4);let out=salsaXor(msg,key,iv);return out.readUInt32LE(0)===0x47375330?out:null}catch{return null}}
function f3(d,o){return[round(rdF(d,o),3),round(rdF(d,o+4),3),round(rdF(d,o+8),3)]}function f4(d,o){return[round(rdF(d,o),2),round(rdF(d,o+4),2),round(rdF(d,o+8),2),round(rdF(d,o+12),2)]}
function flagMap(flags){return{carOnTrack:!!(flags&1),paused:!!(flags&2),loading:!!(flags&4),inGear:!!(flags&8),hasTurbo:!!(flags&16),revLimitAlert:!!(flags&32),handbrake:!!(flags&64),lights:!!(flags&128),highBeams:!!(flags&256),lowBeams:!!(flags&512),asm:!!(flags&1024),tcs:!!(flags&2048)}}
function tyreSpeed(wheelRps, radius){return round((wheelRps||0)*(radius||0)*3.6,2)}function slip(tyreKmh, carKmh){return round((tyreKmh-carKmh)/Math.max(Math.abs(carKmh),1),3)}
const CHANNELS=['velocidade','rpm','marcha','acelerador','freio','combustivelPorcentagem','boostKpa','oilPressure','waterTemp','oilTemp','tyreTemp','tyreSlipRatio','wheelSpeed','suspHeight','position','worldVelocity','rotation','angularVelocity','bodyHeight','orientationNorth','gForce','roadPlane','roadPlaneDistance','clutch','clutchEngagement','rpmClutchGearbox','transmissionTopSpeed','gearRatios','carCode','calcMaxSpeed','minAlertRPM','maxAlertRPM','suggestedGear','flags','surfaceType','currentLapMs','wheelSteeringAngle','wheelBase','carCategory'];
let live={connected:false,status:'aguardando_pacotes',decodeOk:false,updatedAt:null,packetSize:0,packetVersion:'?',ps5Ip:config.ps5Ip,sessionState:'WAITING',currentSessionId:null,velocidade:0,velocidadeMaxima:0,rpm:0,marcha:'N',marchaNumero:0,suggestedGear:null,acelerador:0,freio:0,combustivel:null,combustivelPorcentagem:null,fuelCapacity:null,melhorVolta:'--',ultimaVolta:'--',voltaAtualTempo:'--',tempoTotalCorrida:'--',mediaVoltas:'--',voltasCompletadas:0,voltasCorrigidas:0,voltasCorridas:0,lapTimes:[],analysis:analysis([]),coach:[],lapDebug:{},channels:CHANNELS,note:'Core V4 Raspberry ativo com decoder avançado GT7 UDP'};
let active=null,lastLapMs=0,lastLapNo=0,currentLap=0,currentLapAt=0,movingSince=0,stoppedSince=0,samples=[];
function startSession(name='Nova seção'){active={id:'s-'+Date.now(),name,startedAt:new Date().toISOString(),endedAt:null,laps:[],coach:[],maxSpeed:0,analysis:analysis([])};Object.assign(live,{sessionState:'RUNNING',currentSessionId:active.id,velocidadeMaxima:0,melhorVolta:'--',ultimaVolta:'--',tempoTotalCorrida:'--',mediaVoltas:'--',voltasCompletadas:0,voltasCorrigidas:0,voltasCorridas:0,lapTimes:[],analysis:analysis([]),coach:[]});lastLapMs=0;lastLapNo=0;currentLap=0;currentLapAt=0;samples=[];return active}
function finishSession(name){if(!active)return null;if(name)active.name=String(name).slice(0,80);active.endedAt=new Date().toISOString();active.analysis=analysis(active.laps);active.maxSpeed=live.velocidadeMaxima||active.maxSpeed||0;db.sessions.unshift(active);db.sessions=db.sessions.slice(0,300);if(active.analysis.bestMs)db.ranking.push({sessionId:active.id,name:active.name,date:active.endedAt,bestMs:active.analysis.bestMs,best:active.analysis.best,laps:active.laps.length});db.ranking=db.ranking.sort((a,b)=>a.bestMs-b.bestMs).slice(0,100);saveDb();let done=active;active=null;live.sessionState='FINISHED';live.currentSessionId=null;return done}
function registerLap(ms,no){if(!validLap(ms))return false;if(!active)startSession('Sessão automática');let token=no+':'+ms;if(active.laps.some(l=>l.token===token))return false;let parts=coach(samples.splice(0));let rec={lap:active.laps.length+1,ms,time:fmt(ms),token,at:new Date().toISOString(),maxSpeed:live.velocidadeMaxima,coach:parts,advanced:{tyreTemp:live.tyreTemp,tyreSlipRatio:live.tyreSlipRatio,gForce:live.gForce,boostKpa:live.boostKpa,oilTemp:live.oilTemp,waterTemp:live.waterTemp}};active.laps.push(rec);active.maxSpeed=Math.max(active.maxSpeed||0,live.velocidadeMaxima||0);active.coach.unshift({lap:rec.lap,time:rec.time,parts});active.analysis=analysis(active.laps);Object.assign(live,{analysis:active.analysis,coach:active.coach.slice(0,12),lapTimes:active.laps.map(l=>l.time),tempoTotalCorrida:active.analysis.total,mediaVoltas:active.analysis.average,melhorVolta:active.analysis.best,ultimaVolta:rec.time,voltasCompletadas:active.laps.length,voltasCorrigidas:active.laps.length,voltasCorridas:active.laps.length});return true}
function autoSession(){let now=Date.now(),moving=live.velocidade>20&&live.rpm>1500&&live.marchaNumero>0&&!live.flags?.paused&&!live.flags?.loading;if(!active&&config.autoSession&&moving){movingSince=movingSince||now;if(now-movingSince>5000)startSession('Sessão automática')}else if(!moving)movingSince=0;if(active){let stopped=live.velocidade<5;if(stopped)stoppedSince=stoppedSince||now;else stoppedSince=0;let last=active.laps.length?new Date(active.laps[active.laps.length-1].at).getTime():new Date(active.startedAt).getTime();if(stopped&&now-stoppedSince>30000&&now-last>60000)finishSession()}}
function decode(msg){let d=decrypt(msg);if(!d)return false;let speed=rdF(d,0x4C)*3.6,rpm=rdF(d,0x3C),gearByte=rdU8(d,0x90),gear=gearByte&15,sug=(gearByte>>4)&15,th=rdU8(d,0x91)/2.55,br=rdU8(d,0x92)/2.55,lapNo=rdI16(d,0x74),totalLaps=rdI16(d,0x76),best=rdI32(d,0x78),last=rdI32(d,0x7C),fuel=rdF(d,0x44),cap=rdF(d,0x48),now=Date.now();
let wheelRps=f4(d,0xA4),tyreRadius=f4(d,0xB4),wheelSpeed=wheelRps.map((v,i)=>tyreSpeed(v,tyreRadius[i]));let carKmh=Number.isFinite(speed)?speed:0;let flagsRaw=rdI16(d,0x8E);
Object.assign(live,{lapDebug:{packetSize:d.length,knownOffsets:{currentLap_0x74_i16:lapNo,totalLaps_0x76_i16:totalLaps,bestLap_0x78_i32:best,lastLap_0x7c_i32:last,speed_0x4c:round(rdF(d,0x4c),3),rpm_0x3c:round(rdF(d,0x3c),3),flags_0x8e:flagsRaw,gears_0x90:gearByte}},velocidade:Number.isFinite(speed)&&speed>=0&&speed<600?Math.round(speed):0,rpm:Number.isFinite(rpm)&&rpm>=0&&rpm<20000?Math.round(rpm):0,marcha:gear===0?'N':String(gear),marchaNumero:gear,suggestedGear:sug===15?null:sug,acelerador:clamp(Math.round(th),0,100),freio:clamp(Math.round(br),0,100),combustivel:Number.isFinite(fuel)?round(fuel,2):null,fuelCapacity:Number.isFinite(cap)?round(cap,2):null,combustivelPorcentagem:cap>0?Math.round(fuel/cap*100):null,totalLaps:totalLaps>0?totalLaps:0,position:f3(d,0x04),worldVelocity:f3(d,0x10),rotation:f3(d,0x1C),orientationNorth:round(rdF(d,0x28),3),angularVelocity:f3(d,0x2C),bodyHeight:round(rdF(d,0x38),3),boost:round(rdF(d,0x50),3),boostKpa:round((rdF(d,0x50)-1)*100,2),oilPressure:round(rdF(d,0x54),2),waterTemp:round(rdF(d,0x58),1),oilTemp:round(rdF(d,0x5C),1),tyreTemp:f4(d,0x60),packetId:rdI32(d,0x70),dayProgression:rdI32(d,0x80),raceStartPosition:rdI16(d,0x84),preRaceNumCars:rdI16(d,0x86),minAlertRPM:rdI16(d,0x88),maxAlertRPM:rdI16(d,0x8A),calcMaxSpeed:rdI16(d,0x8C),flagsRaw,flags:flagMap(flagsRaw),roadPlane:f3(d,0x94),roadPlaneDistance:round(rdF(d,0xA0),3),wheelRps,wheelSpeed,tyreRadius,suspHeight:f4(d,0xC4),clutch:round(rdF(d,0xF4),3),clutchEngagement:round(rdF(d,0xF8),3),rpmClutchGearbox:Math.round(rdF(d,0xFC)),transmissionTopSpeed:round(rdF(d,0x100),3),gearRatios:[0,1,2,3,4,5,6,7].map(i=>round(rdF(d,0x104+i*4),4)),carCode:rdI32(d,0x124)});
if(d.length>=0x13C){Object.assign(live,{wheelRotation:round(rdF(d,0x128),3),steeringAngularVelocity:round(rdF(d,0x12C),3),gForce:{lateral:round(rdF(d,0x130),3),vertical:round(rdF(d,0x134),3),longitudinal:round(rdF(d,0x138),3)},sway:round(rdF(d,0x130),3),heave:round(rdF(d,0x134),3),surge:round(rdF(d,0x138),3)})}
if(d.length>=0x158){Object.assign(live,{throttleFiltered:rdU8(d,0x13C),brakeFiltered:rdU8(d,0x13D),torqueVectors:f4(d,0x140),energyRecovery:round(rdF(d,0x150),3)})}
if(d.length>=0x170){live.surfaceType=d.subarray(0x158,0x15C).toString('ascii').replace(/\0/g,'');live.currentLapMs=rdI32(d,0x15C);live.currentLapTime=fmt(live.currentLapMs);live.wheelSteeringAngle=[round(rdF(d,0x160),4),round(rdF(d,0x164),4)];live.wheelBase=round(rdF(d,0x168),3);live.carCategory=d.subarray(0x16C,0x170).toString('ascii').replace(/\0/g,'')}
live.tyreSlipRatio=wheelSpeed.map(v=>slip(v,live.velocidade));if(active)live.velocidadeMaxima=Math.max(live.velocidadeMaxima,live.velocidade);samples.push({speed:live.velocidade,rpm:live.rpm,throttle:live.acelerador,brake:live.freio,at:now,gForce:live.gForce,tyreSlipRatio:live.tyreSlipRatio});if(samples.length>1000)samples=samples.slice(-1000);if(lapNo>0&&lapNo!==currentLap){currentLap=lapNo;currentLapAt=now}live.voltaAtualTempo=currentLapAt&&lapNo>0?fmt(now-currentLapAt):'--';if(!active&&best>0)live.melhorVolta=fmt(best);if(last>0&&lapNo>1&&(last!==lastLapMs||lapNo!==lastLapNo)){lastLapMs=last;lastLapNo=lapNo;registerLap(last,lapNo)}autoSession();live.decodeOk=true;live.status='recebendo_udp_decodificado';live.note='Core V4 processando no Raspberry com canais GT7 UDP avançados';return true}
function resetLive(){startSession('Nova seção');Object.assign(live,{velocidade:0,rpm:0,marcha:'N',marchaNumero:0,acelerador:0,freio:0,combustivel:null,combustivelPorcentagem:null})}
function js(res,obj,code=200){res.writeHead(code,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(obj))}function body(req){return new Promise(r=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>r(b))})}
const udp=dgram.createSocket('udp4'),hb=dgram.createSocket('udp4');udp.on('message',msg=>{live.connected=true;live.updatedAt=Date.now();live.packetSize=msg.length;live.packetVersion=msg.length===368?'C':msg.length===296?'A':msg.length===316?'B':msg.length===348?'~':'?';live.ps5Ip=config.ps5Ip;if(!decode(msg)){live.decodeOk=false;live.status='recebendo_udp_sem_decode'}});udp.bind(UDP_PORT,'0.0.0.0',()=>console.log('UDP ouvindo '+UDP_PORT));setInterval(()=>{let b=Buffer.from('A');hb.send(b,0,b.length,PS5_PORT,config.ps5Ip,()=>{});if(live.updatedAt&&Date.now()-live.updatedAt>5000){live.connected=false;live.status='aguardando_pacotes'}},1000);
http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return js(res,{ok:true});let u=new URL(req.url,'http://x');if(u.pathname==='/'||u.pathname==='/api/health')return js(res,{ok:true,app:'Telemetria v4 Core Raspberry',version:4,status:live.status,sessionState:live.sessionState,endpoints:['/api/fields','/api/channels','/api/current-session','/api/sessions','/api/ranking','/api/coach','/api/session/start','/api/session/finish','/api/reset','/api/config']});if(['/api/fields','/api/live','/api/telemetry'].includes(u.pathname))return js(res,live);if(u.pathname==='/api/channels')return js(res,{ok:true,channels:CHANNELS,advanced:true,source:'gt7-udp-2.1.1 + sim-to-motec channels'});if(u.pathname==='/api/current-session')return js(res,{ok:true,active,live});if(u.pathname==='/api/sessions'&&req.method==='GET')return js(res,{ok:true,sessions:db.sessions,active});if(u.pathname==='/api/ranking')return js(res,{ok:true,ranking:db.ranking});if(u.pathname==='/api/coach')return js(res,{ok:true,coach:live.coach});if(u.pathname==='/api/debug-laps')return js(res,{ok:true,lapDebug:live.lapDebug,lapTimes:live.lapTimes,analysis:live.analysis});if(u.pathname==='/api/config'&&req.method==='GET')return js(res,{ok:true,config,bridge:{port:PORT,udpPort:UDP_PORT,ps5Port:PS5_PORT},dataFile:DB_FILE});if(u.pathname==='/api/config'&&req.method==='POST'){try{let j=JSON.parse(await body(req)||'{}');if(j.ps5Ip){config.ps5Ip=String(j.ps5Ip).trim();live.ps5Ip=config.ps5Ip}if(typeof j.autoSession==='boolean')config.autoSession=j.autoSession;saveConfig();return js(res,{ok:true,config})}catch(e){return js(res,{ok:false,error:String(e)},400)}}if(u.pathname==='/api/session/start'&&req.method==='POST'){let j={};try{j=JSON.parse(await body(req)||'{}')}catch{}return js(res,{ok:true,session:startSession(j.name||'Nova seção')})}if(u.pathname==='/api/session/finish'&&req.method==='POST'){let j={};try{j=JSON.parse(await body(req)||'{}')}catch{}return js(res,{ok:true,session:finishSession(j.name)})}if(u.pathname==='/api/sessions'&&req.method==='POST'){try{let j=JSON.parse(await body(req)||'{}'),s=active?finishSession(j.name):{id:'manual-'+Date.now(),name:String(j.name||'Seção manual').slice(0,80),startedAt:j.date||new Date().toISOString(),endedAt:new Date().toISOString(),laps:j.lapRecords||[],analysis:j.analysis||{},maxSpeed:j.max||0};if(s&&!db.sessions.some(x=>x.id===s.id)){db.sessions.unshift(s);saveDb()}return js(res,{ok:true,session:s,count:db.sessions.length})}catch(e){return js(res,{ok:false,error:String(e)},400)}}if(u.pathname==='/api/reset'&&req.method==='POST'){resetLive();return js(res,{ok:true,live})}return js(res,{ok:true,app:'Telemetria v4 Core Raspberry'})}).listen(PORT,'0.0.0.0',()=>console.log('HTTP em '+PORT+' PS5='+config.ps5Ip));
