services:
  gt7-telemetria-next:
    build: .
    container_name: gt7-telemetria-next
    network_mode: host
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HTTP_PORT: 8790
      UDP_RECEIVE_PORT: 33740
      PS5_HEARTBEAT_PORT: 33739
      PS5_IP: 192.168.1.81
      DATA_DIR: /app/data
    volumes:
      - ./data:/app/data
